bump_version: null
lint:
  files_exist:
    - conf/igenomes.config
  nextflow_config:
    - config_defaults:
        - params.dfast_config
nf_core_version: 3.0.2
org_path: null
repository_type: pipeline
template:
  author: Andreas Wilm, Alexander Peltzer
  description: Simple bacterial assembly and annotation
  force: false
  is_nfcore: true
  name: bacass
  org: nf-core
  outdir: .
  skip_features:
    - igenomes
  version: 2.4.0
update: null
