lint:
  files_unchanged:
    - .github/PULL_REQUEST_TEMPLATE.md
  files_exist:
    - conf/igenomes.config
  nextflow_config:
    - config_defaults:
        - params.dfast_config
nf_core_version: 3.3.2
repository_type: pipeline
template:
  author: Andreas Wilm, Alexander Peltzer
  description: Simple bacterial assembly and annotation
  force: false
  is_nfcore: true
  name: bacass
  org: nf-core
  outdir: .
  skip_features:
    - igenomes
